(() => {
'use strict';
const KEY='alex-darby-build-v2';
const boxes=[...document.querySelectorAll('[data-step]')];
const status=document.querySelector('#feedback');
let timer, storageWorks=true;
let saved={};
try { const data=JSON.parse(localStorage.getItem(KEY)||'{}'); if(data && typeof data==='object' && !Array.isArray(data)) saved=data; const old=JSON.parse(localStorage.getItem('alex-darby-build-v1')||'{}'); const count=old && typeof old==='object'?Object.values(old).filter(v=>v===true).length:0; if(count){const legacy=document.querySelector('#legacy');legacy.hidden=false;legacy.textContent=`Your earlier guide had ${Math.min(count,8)} of 8 checked. Those records are kept. This edition has revised steps, so review them again.`;} } catch { saved={}; }
function announce(text){status.textContent=text;clearTimeout(timer);timer=setTimeout(()=>{status.textContent='';},6000);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(Object.fromEntries(boxes.map(b=>[b.dataset.step,b.checked]))));}catch{storageWorks=false;document.querySelector('#save-note').textContent='Browser storage is unavailable. Checkmarks work for this visit but will not survive a reload.';}}
function refresh(){const n=boxes.filter(b=>b.checked).length;document.querySelector('#progress').value=n;document.querySelector('#progress-text').textContent=`${n} of 8 reviewed`;boxes.forEach((b,i)=>{b.closest('.step').classList.toggle('complete',b.checked);document.querySelectorAll('#step-nav a')[i].classList.toggle('done',b.checked);});const next=boxes.find(b=>!b.checked);const target=next?'#'+next.closest('.step').id:'#finish';document.querySelector('#resume').href=target;document.querySelector('#resume').textContent=next?'Go to next step →':'Your build review is complete →';document.querySelector('#finish').hidden=n!==8;document.querySelector('#begin').textContent=n>0?'Continue your build ↗':'Let’s get started ↗';document.querySelector('#begin').href=n>0?target:'#start';}
boxes.forEach(b=>{b.checked=saved[b.dataset.step]===true;b.addEventListener('change',()=>{save();refresh();});});
// Detect disabled storage before implying that progress can be retained.
try{localStorage.setItem(KEY+'-check','1');localStorage.removeItem(KEY+'-check');}catch{storageWorks=false;document.querySelector('#save-note').textContent='Browser storage is unavailable. Checkmarks work for this visit but will not survive a reload.';}
refresh();
const starters={event:{text:'Draft an event plan from these sample details: 12 guests, Thursday, a 2 p.m. arrival, and a 90-minute visit. Return an itinerary, a requirements checklist, and questions about missing information. The date, location, transport, and accessibility arrangements are unconfirmed. Do not invent them or contact anyone.',result:'Look for: the supplied timing, a clear checklist, and questions about the missing details.'},capacity:{text:'Help me check mentor capacity using sample numbers: 12 scholars, 4 mentors, and 2 available hours per mentor per week. Calculate total mentor hours and an equal-share estimate per scholar. List assumptions and missing requirements. Do not assign people, decide a budget, or make commitments.',result:'Check the math: 8 mentor-hours per week; an equal share is 40 minutes per scholar. Real capacity depends on meeting format and other duties.'},update:{text:'Turn these sample program notes into a short draft update: venue confirmed; mentor availability still pending; budget not yet approved. Use three sections: confirmed updates, waiting items, and questions for Alex. Keep it plain and practical. Do not invent deadlines, approvals, or commitments. Do not send it.',result:'Look for: confirmed facts separated from pending decisions, with no invented deadline.'}};
function setStarter(key){document.querySelector('#starter-prompt').textContent=starters[key].text;document.querySelector('#starter-result').textContent=starters[key].result;document.querySelectorAll('[data-starter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.starter===key)));}
document.querySelectorAll('[data-starter]').forEach(b=>b.addEventListener('click',()=>setStarter(b.dataset.starter)));setStarter('event');
document.querySelectorAll('.copy').forEach(button=>button.addEventListener('click',async()=>{const el=button.dataset.copy?document.getElementById(button.dataset.copy):button.parentElement.querySelector('code');try{await navigator.clipboard.writeText(el.textContent);announce('Copied. Review the text before using it.');}catch{const range=document.createRange();range.selectNodeContents(el);const selection=window.getSelection();selection.removeAllRanges();selection.addRange(range);announce('Copy is unavailable. Text selected: use your device’s Copy command.');}}));
const dialog=document.querySelector('#reset-dialog');document.querySelector('#reset').addEventListener('click',()=>dialog.showModal());document.querySelector('#cancel-reset').addEventListener('click',()=>dialog.close());document.querySelector('#confirm-reset').addEventListener('click',()=>{boxes.forEach(b=>b.checked=false);save();refresh();dialog.close();announce(storageWorks?'Checkmarks reset.':'Checkmarks reset for this visit.');});
function updateEmail(){const question=document.querySelector('#question').value.trim();const subject=encodeURIComponent('Alex x OpenClaw: a setup question');const body=encodeURIComponent((question || 'Step:\nWhat I expected:\nWhat happened:')+'\n\nFrom Alex Builds a Darby · October 2026 guide');document.querySelector('#askmail').href=`mailto:gbellamyAI@gmail.com?cc=gbellamy@gmail.com&subject=${subject}&body=${body}`;}
document.querySelector('#question').addEventListener('input',updateEmail);
document.querySelector('#help-form').addEventListener('submit',e=>e.preventDefault());updateEmail();
document.querySelector('#print').addEventListener('click',()=>window.print());
})();
