const {chromium}=require(process.env.PLAYWRIGHT_PATH || '/Users/gordonai/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');
fs.mkdirSync('review',{recursive:true});
if(!fs.existsSync('review/before.html')) fs.writeFileSync('review/before.html',require('child_process').execFileSync('git',['show','fda81ac1b86afe1302bd0e6089a43b0a7a7e81f8:index.html']));
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write'],reducedMotion:'reduce'});const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));const checks=[];function check(name,ok){checks.push({name,passed:!!ok});if(!ok)throw Error(name);}
await p.goto('http://127.0.0.1:8765/review/before.html');await p.screenshot({path:'review/before-desktop.png'});await p.goto('http://127.0.0.1:8765');await p.screenshot({path:'review/desktop.png',fullPage:true});await p.screenshot({path:'review/desktop-first-screen.png'});
check('all 8 steps render',await p.locator('.step').count()===8);
await p.keyboard.press('Tab');check('keyboard skip link first',await p.locator('.skip').evaluate(e=>e===document.activeElement));await p.keyboard.press('Enter');check('skip link routes to setup',p.url().endsWith('#start'));
for(let i=0;i<3;i++){await p.locator('nav a[href="#step-4"]').click();check('repeated installed navigation '+i,p.url().endsWith('#step-4'));await p.locator('nav a[href="#help"]').click();await p.locator('.brand').click();}
const first=p.locator('[data-step="basics"]');await first.focus();await p.keyboard.press('Space');check('keyboard toggles progress',(await p.locator('#progress-text').textContent()).startsWith('1 of 8'));await p.reload();check('progress survives reload',await first.isChecked());check('resume skips completed',await p.locator('#resume').getAttribute('href')==='#step-2');
await p.locator('#reset').click();await p.locator('#cancel-reset').click();check('cancel reset preserves progress',await first.isChecked());await p.locator('#reset').click();await p.keyboard.press('Escape');check('escape dismisses reset',!await p.locator('dialog').isVisible());
for(const b of await p.locator('[data-step]').all())await b.check();check('completion message appears',await p.locator('#finish').isVisible());await p.screenshot({path:'review/completion.png',fullPage:false});
await p.locator('#reset').click();await p.locator('#confirm-reset').click();await p.reload();check('reset persists',(await p.locator('#progress-text').textContent()).startsWith('0 of 8'));
for(const key of ['capacity','update','event','capacity']){await p.locator(`[data-starter="${key}"]`).click();check('starter '+key,await p.locator(`[data-starter="${key}"]`).getAttribute('aria-pressed')==='true');}
await p.locator('[data-copy="starter-prompt"]').click();check('clipboard copies full starter',(await p.evaluate(()=>navigator.clipboard.readText())).includes('12 scholars'));
await p.evaluate(()=>Object.defineProperty(navigator,'clipboard',{value:{writeText:()=>Promise.reject(Error('blocked'))},configurable:true}));await p.locator('[data-copy="starter-prompt"]').click();check('clipboard denial selects complete text',(await p.evaluate(()=>window.getSelection().toString())).includes('12 scholars'));check('clipboard failure explained',(await p.locator('#feedback').textContent()).includes('Copy is unavailable'));
await p.locator('#question').fill('Step 4: A & B? café\nNo token.');const mail=await p.locator('#help-form').evaluate(form=>{const original=Event.prototype.preventDefault;let found='';const handler=e=>{};return {text:form.querySelector('textarea').value,required:form.querySelector('textarea').required};});check('help has required labeled input',mail.required && await p.locator('label[for="question"]').count()===1);
const mailURL=new URL(await p.locator('#askmail').getAttribute('href'));check('mailto retains exact destination and CC',mailURL.pathname==='gbellamyAI@gmail.com' && mailURL.searchParams.get('cc')==='gbellamy@gmail.com');check('mailto correctly encodes punctuation unicode and newline',mailURL.searchParams.get('body').startsWith('Step 4: A & B? café\nNo token.'));
const links=await p.locator('a[href]').evaluateAll(es=>es.map(e=>e.getAttribute('href')));check('all internal links resolve',await p.evaluate(()=>[...document.querySelectorAll('a[href^="#"]')].every(a=>document.getElementById(a.hash.slice(1)))));fs.writeFileSync('review/links.json',JSON.stringify([...new Set(links.filter(x=>x.startsWith('http')))],null,2));
await p.evaluate(()=>{localStorage.setItem('alex-darby-build-v1',JSON.stringify({s1:true,s3:true}));localStorage.setItem('alex-darby-build-v2','null');});await p.reload();check('legacy progress preserved and disclosed',(await p.locator('#legacy').textContent()).includes('2 of 8') && await p.evaluate(()=>JSON.parse(localStorage.getItem('alex-darby-build-v1')).s1));
await p.evaluate(()=>localStorage.setItem('alex-darby-build-v2','{bad'));await p.reload();check('corrupt storage does not break page',await p.locator('.step').count()===8);
for(const width of [320,390,768,1440]){await p.setViewportSize({width,height:900});await p.goto('http://127.0.0.1:8765');check('no page overflow at '+width,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width===390){await p.screenshot({path:'review/phone.png',fullPage:true});await p.screenshot({path:'review/phone-first-screen.png'});await p.locator('#step-2').scrollIntoViewIfNeeded();await p.screenshot({path:'review/phone-setup.png'});await p.locator('#step-7').scrollIntoViewIfNeeded();await p.locator('[data-starter="capacity"]').click();await p.screenshot({path:'review/phone-starter.png'});}}
const blocked=await browser.newContext({viewport:{width:390,height:844}});await blocked.addInitScript(()=>Object.defineProperty(window,'localStorage',{get(){throw Error('blocked')}}));const b=await blocked.newPage();await b.goto('http://127.0.0.1:8765');await b.locator('[data-step="basics"]').check();check('storage blocked still usable',(await b.locator('#save-note').textContent()).includes('unavailable') && (await b.locator('#progress-text').textContent()).startsWith('1 of 8'));
const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const n=await nojs.newPage();await n.goto('http://127.0.0.1:8765');check('no-JS guide remains readable',await n.locator('.step').count()===8 && await n.locator('#start noscript').isVisible());
await p.emulateMedia({media:'print'});await p.pdf({path:'review/print-preview.pdf',format:'A4',printBackground:true});check('no runtime errors',errors.length===0);fs.writeFileSync('review/browser-tests.json',JSON.stringify({date:new Date().toISOString(),browser:await browser.version(),checks,errors,limitations:['Browser viewport emulation, not a physical phone.','OpenClaw commands documentation-reviewed; not executed.','Email app delivery not exercised.']},null,2));await browser.close();console.log(JSON.stringify({passed:checks.length,errors}));})().catch(e=>{console.error(e);process.exit(1)});
